In [11]:
from plyfile import PlyData
import pandas as pd
import numpy as np
import os
import open3d as o3d

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [5]:
label_item_path = 'D:/sunny/Codes/DPS/data_teethseg/label/000101.ply'
raw_data = PlyData.read(label_item_path)  # read ply file
points = np.array(pd.DataFrame(raw_data.elements[0].data)) # [x, y, z, r, g, b]
faces = np.array(pd.DataFrame(raw_data.elements[1].data)) # [vertex1_idx, vertex2_idx, vertex3_idx]

n_face = faces.shape[0]  # number of faces

In [15]:
print(points.shape)
print(points[:5,:])
# Set the print options to suppress scientific notation and print in normal number format
np.set_printoptions(suppress=True, precision=4)

(20615, 9)
[[ -9.1111   9.58    25.6032  -0.4266   0.6083   0.6693 255.     255.
  255.    ]
 [ -8.9617   9.8557  25.4659  -0.4114   0.6708   0.6171 255.     255.
  255.    ]
 [ -9.0966   9.9119  25.2929  -0.3896   0.738    0.551  255.     255.
  255.    ]
 [ -9.3256   9.4688  25.5926  -0.2491   0.6316   0.7342 255.     255.
  255.    ]
 [ -8.937    9.6079  25.7075  -0.4048   0.5736   0.7121 255.     255.
  255.    ]]


In [16]:
print(faces.shape)
print(faces[:5,:])

(39985, 1)
[[array([2, 0, 1], dtype=uint32)]
 [array([4, 1, 0], dtype=uint32)]
 [array([5, 0, 2], dtype=uint32)]
 [array([0, 5, 3], dtype=uint32)]
 [array([6, 1, 4], dtype=uint32)]]


In [17]:
# load mesh via open3d
mesh = o3d.io.read_triangle_mesh(label_item_path)
points_o3d = np.asarray(mesh.vertices)
faces_o3d = np.asarray(mesh.triangles)
normals = np.asarray(mesh.vertex_normals)

print(points_o3d[:5,:])
print(faces_o3d[:5,:])
print(normals[:5,:])

[[-9.1111  9.58   25.6032]
 [-8.9617  9.8557 25.4659]
 [-9.0966  9.9119 25.2929]
 [-9.3256  9.4688 25.5926]
 [-8.937   9.6079 25.7075]]
[[2 0 1]
 [4 1 0]
 [5 0 2]
 [0 5 3]
 [6 1 4]]
[[-0.4266  0.6083  0.6693]
 [-0.4114  0.6708  0.6171]
 [-0.3896  0.738   0.551 ]
 [-0.2491  0.6316  0.7342]
 [-0.4048  0.5736  0.7121]]
