In [9]:
from plyfile import PlyData
import pandas as pd
import numpy as np
import os
import open3d as o3d

np.set_printoptions(suppress=True, precision=3)

In [4]:
label_item_path = 'D:/sunny/Codes/DPS/data_8w/3d_ply/label/000101.ply'
raw_data = PlyData.read(label_item_path)  # read ply file
points = np.array(pd.DataFrame(raw_data.elements[0].data)) # [x, y, z, r, g, b]
faces = np.array(pd.DataFrame(raw_data.elements[1].data)) # [vertex1_idx, vertex2_idx, vertex3_idx]

n_face = faces.shape[0]  # number of faces

In [10]:
print(points.shape)
print(points[:5,:])
# Set the print options to suppress scientific notation and print in normal number format


(40992, 9)
[[ -8.745   9.571  25.572  -0.397   0.606   0.689 255.    255.    255.   ]
 [ -8.681   9.846  25.384  -0.441   0.629   0.637 255.    255.    255.   ]
 [ -8.514   9.849  25.482  -0.354   0.694   0.627 255.    255.    255.   ]
 [ -8.846   9.739  25.359  -0.399   0.626   0.67  255.    255.    255.   ]
 [ -8.975   9.522  25.507  -0.211   0.639   0.739 255.    255.    255.   ]]


In [11]:
print(faces.shape)
print(faces[:5,:])

(79999, 1)
[[array([3, 0, 1], dtype=uint32)]
 [array([5, 1, 0], dtype=uint32)]
 [array([1, 5, 2], dtype=uint32)]
 [array([6, 0, 3], dtype=uint32)]
 [array([0, 6, 4], dtype=uint32)]]


In [12]:
# load mesh via open3d
mesh = o3d.io.read_triangle_mesh(label_item_path)
points_o3d = np.asarray(mesh.vertices)
faces_o3d = np.asarray(mesh.triangles)
normals = np.asarray(mesh.vertex_normals)

print(points_o3d[:5,:])
print(faces_o3d[:5,:])
print(normals[:5,:])

[[-8.745  9.571 25.572]
 [-8.681  9.846 25.384]
 [-8.514  9.849 25.482]
 [-8.846  9.739 25.359]
 [-8.975  9.522 25.507]]
[[3 0 1]
 [5 1 0]
 [1 5 2]
 [6 0 3]
 [0 6 4]]
[[-0.397  0.606  0.689]
 [-0.441  0.629  0.637]
 [-0.354  0.694  0.627]
 [-0.399  0.626  0.67 ]
 [-0.211  0.639  0.739]]
